### ISSUE TITLE
selenium 效率好像有点慢

### ISSUE THREAD

**Issue by WhaleFell** [sethome2/paper-download#1]
> 个人意见哈

**Comment by sethome2** [comment]
哈哈哈，也许我需要这个许可证(*￣3￣)╭https://github.com/me-shaon/GLWTPL

暂时没有修改的想法，也许后面会做吧，留给自己用的小工具，现在这个是用来教学的产物。

html静态解析可能快一点，配合一个小的数据库。能到这个水平的话，solo要好久。

**Comment by WhaleFell** [comment]
嗯嗯，晓得，加油加油😙🙌🙌
